### ISSUE TITLE
Make a physical button that sends a text

### ISSUE THREAD

**Issue by douglasnaphas** [douglasnaphas/summoning-button#1]

**Comment by douglasnaphas** [comment]
# TODO
- [x] Publish to the SNS topic that sends me a text from the CLI, and receive a text.
- [ ] Make a Lambda that publishes to an SNS topic to send a text. Get it so that I can invoke the Lambda from the AWS CLI and receive a text. The Lambda can optionally take parameters, because I can attach parameters to the event that will come from IoT 1-Click.
- [ ] What happens if more than one origination number is available for SNS? How does a topic or subscription know which origination number texts are supposed to come from?
